<?php
/**
 * @file
 */

/**
 * Callback to return a list of FoA units and schools.
 */
function _unimelb_arts_webform_unit_school() {
  return array(
    'Arts Executive Office' => t('Arts Executive Office'),
    'Arts Business Centre' => t('Arts Business Centre'),
    'Graduate Studies' => t('Office of Graduate Studies'),
    'Arts Student Centre' => t('Arts Student Centre'),
    'Asia Institute' => t('Asia Institute'),
    'Culture and Communication' => t('School of Culture and Communication'),
    'School of Historical and Philosophical Studies' => t('School of Historical and Philosophical Studies'),
    'Languages and Linguistics' => t('School of Languages and Linguistics'),
    'Social and Political Sciences' => t('School of Social and Political Sciences'),
  );
}
