<?php
/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function uom_webform_remedy_menu() {
  $items['node/%webform_menu/webform/remedy'] = array(
    'title' => 'BSM Remedy',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uom_webform_remedy_form', 1),
    'access callback' => 'node_access',
    'access arguments' => array('update', 1),
    'file' => 'uom_webform_remedy.remedy.inc',
    'weight' => 5,
    'type' => MENU_LOCAL_TASK,
  );
}

/**
 * Implements hook_node_insert().
 */
function uom_webform_remedy_node_insert($node) {
  if (!variable_get('webform_node_' . $node->type, FALSE)) {
    return;
  }
}

/**
 * Implements hook_node_load().
 *
 * @see webform_node_load().
 */
function uom_webform_remedy_node_load($nodes, $types) {
  // Quick check to see if we need to do anything at all for these nodes.
  $webform_types = webform_node_types();
  if (count(array_intersect($types, $webform_types)) == 0) {
    return;
  }

  // Select all webforms that match these node IDs.
  $result = db_select('uom_webform_remedy')
    ->fields('remedy', 'remedy_url')
    ->condition('nid', array_keys($nodes), 'IN')
    ->execute()
    ->fetchAllAssoc('nid', PDO::FETCH_ASSOC);

  foreach ($result as $nid => $remedy) {
    dpm($remedy);
  }

}

/**
 * Implements hook_webform_node_defaults_alter().
 */
function uom_webform_remedy_webform_node_defaults_alter(&$defaults) {
  $defaults['remedy'] = array();
}
